FROM golang:1.17-alpine3.15 as builder

WORKDIR /app

COPY ./ ./
COPY ./go.mod ./

RUN go mod tidy -go=1.16 && \
	go mod tidy -go=1.17 && \
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o payments/cmd payments/cmd/payments.go

FROM alpine:3.15.0

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/payments/cmd/payments /app/payments

ENTRYPOINT [ "/app/payments" ]