FROM golang:1.17-alpine3.15 as builder

ARG TARGETARCH
ARG TARGETOS

WORKDIR /app

COPY ./ ./
COPY ./go.mod ./

RUN go mod tidy -go=1.16 && \
	go mod tidy -go=1.17 && \
	CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o orders/cmd orders/cmd/orders.go

FROM alpine:3.15.0

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/orders/cmd/orders /app/orders

ENTRYPOINT [ "/app/orders" ]