FROM golang:1.17-alpine3.15 as builder

ARG TARGETARCH
ARG TARGETOS

WORKDIR /build

COPY ./ ./

RUN go mod tidy -go=1.17 && \
	CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o customers/cmd customers/cmd/customers.go

FROM alpine:3.15.0

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /build/customers/cmd/customers /app/customers
COPY ./configs/customers.hcl /app/configs/customers.hcl

USER 1000

ENTRYPOINT [ "/app/customers" ]